// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hexbltvslhcbhqdcrivq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhleGJsdHZzbGhjYmhxZGNyaXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MzIxMjQsImV4cCI6MjA3ODAwODEyNH0.AvKQ-pOO3iOn024nq2rdiABG01lKP2wEShpWDPQCzfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});